Miniconda is a small version of Anaconda, with python 3.9, https://docs.conda.io/en/latest/miniconda.html
prepending to __UENV: miniconda3-py39
prepending to PATH: /opt/miniconda39/bin
prepending to LD_LIBRARY_PATH: /opt/miniconda39/lib
prepending to LD_LIBRARY_PATH: /usr/lib64/openmpi/lib
sourcing environment file /opt/miniconda39/etc/profile.d/conda.sh


Requirement already satisfied: pandas in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: matplotlib in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (3.10.1)
Requirement already satisfied: seaborn in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: six>=1.5 in /home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/mnt/beegfs/home/ricardor/bachelor/German-News-Data-Classification-COPY/src/logit_analysis.py", line 7, in <module>
    df = pd.read_csv('./pictures/e5_finetuned_model_predictions_with_logits.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/stud/ricardor/.conda/envs/news_classification/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './pictures/e5_finetuned_model_predictions_with_logits.csv'
